### ISSUE TITLE
Metadata Schemas

### ISSUE THREAD

**Issue by blaiszik** [Garden-AI/garden#10]
We should agree on initial schemas for:

1. Model information (evaluate MLFlow, DLHub, HF schemas)
2. General information (e.g. authors, titles, etc. via Datacite)
3. Testing information (e.g., results of reliability testing)
4. Benchmarks

The goal is to create example records so that we can begin work on the front end ASAP

**Comment by WardLT** [comment]
Should this supersede #4 ?

**Comment by blaiszik** [comment]
Moved this as part of the discussion on #4
