### ISSUE TITLE
Make PyTorch and TensorFlow flavor support testable in CI

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#105]
Follow-up to #73. We have new flavors that we support but we can't yet test our support for them in CI. Also, it would be good for new developers to optionally install the backing libraries in the same way that they can optionally install the libraries used for testing.

# Assumptions:
1. PyTorch and TensorFlow should not be included in the default garden-ai PyPI package.
2. There should be a way for devs to issue a poetry command that installs versions of PyTorch and TensorFlow that are known to work/install well with the rest of the libraries we depend on.

# Acceptance Criteria
Given a new PR after this PR, when we run CI/CD, then there will be tests run that exercise our flavor support. But pytorch and tensorflow won't be included in our default base garden-ai package.

**Comment by steve-barnard** [comment]
@WillEngler no rush, but wanted to confirm if PR #107 completes this issue.

**Comment by WillEngler** [comment]
It does, yes! Thanks again, closing
