### ISSUE TITLE
Design Model Manifest

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#11]
_As Developers, we need to consider and design the schema we want for our model manifest_

Related to https://github.com/Garden-AI/garden/issues/4#issuecomment-1278195228 

# Assumptions:
1. We have considered and are familiar with existing schemas for model description, including DLHub's dlhub.json, the ml-flow schema, and the HuggingFace model cards 

# Acceptance Criteria
Given we have discussed the pros and cons of different ways of describing a Garden model (including the dlhub.json, ml-flow schema, and HuggingFace model cards, etc), and that we have done research on each, we can:
- Agree on what needs to be included for effective model description by a Publisher, and what does not
- Agree on what works best across our existing dlhub.json, the ml-flow schema, and the HuggingFace model cards (and any other schemas)
- Present to the team a coherent model schema template

**Comment by WardLT** [comment]
I put a starting effort into implementing our ideas as Pydantic classes. Does this hit the mark from our meeting today? 

https://github.com/Garden-AI/garden/blob/manifests_lw/garden/manifests.py

**Comment by WardLT** [comment]
Yes, because you can use Pydantic to generate the JSON schema.

**Comment by ascourtas** [comment]
Codegen for data validation? https://pydantic-docs.helpmanual.io/datamodel_code_generator/

**Comment by WardLT** [comment]
That's a good idea. I was thinking of building validation into the `DataType` classes, but the more we can avoid the better :)

**Comment by BenGalewsky** [comment]
This has triggered some great discussions, however I would like to propose, in the agile spirit, that we de-scope this story and focus on the title, description, and DataCite properties. We can then proceed with a story to generate just this part of the manifest, publish it and work on a story for consumers to search and retrieve them.

Meanwhile we can talk more about what a pipeline looks like.

I would like us to dig up from our collaborators some first examples of models they will want to publish and follow along as examples.

**Comment by ascourtas** [comment]
I am pro limiting the scope! For context, I just posted the `codegen` link because Ben B had suggested it in slack and I didn't want it to get lost -- in the future I can add a little more context when copying things over from slack. 

I think limiting to simple metadata is very reasonable and sounds like a great idea. We could use Logan's model he just used in his web runner (I forget the name)?

I am assuming we'd still want to explore the different schema solutions (ie Pydantic, mlflow, etc) and compare in GT next week? Or do you think that's still too broad Ben G?

**Comment by WardLT** [comment]
Per Friday's discussion and @BenGalewsky 's scrum wisdom, we want just enough to be able to create a landing page for a model
- [ ] DataCite
- [ ] Model identifier (/ title?)
- [ ] Who published the model
- [ ] When was the model published
- [ ] (other things that we might be obviously missing, but nothing non-obvious!)

Follow up with the other details once we have an idea of what the models look like (i.e., after we survey the PIs for their initial models)

**Comment by ascourtas** [comment]
I believe we decided to table this until we had a better idea of model consumer needs via Consumer Stories? Which triggered excellent design/nomenclature questions

Some ideas here: https://miro.com/app/board/uXjVOxpxyXY=/?moveToWidget=3458764537364886952&cot=14
