### ISSUE TITLE
Create shortlist of models to migrate from DLHub

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#114]
_As a User, I want to make sure any model I've put my blood/sweat/tears into on DLHub is available and usable in Garden, in gardens I have access to. I also want to know that any of my unusuable models and/or tests are *not* in Garden_

Related to #112 

# Assumptions:
1. We are able to migrate models in #112 
2. We only migrate models that belong to real users (ie UWisc, Eliu's group, and other indie publishers), not the dev team. 
3. We only migrate models that actually work and are desired by their publishers (eg we don't publish old versions that the user does not want visible)

# Acceptance Criteria
1. Given a model name/DOI and publisher username, we can programmatically determine whether it's probably a real "keeper" model desired by users, or a test from the dev team. 
2. Given a username or group of users (eg "UWisc"), we ask the users (via email) which models of all of their versions they actually want to keep (because there's a lot of defunct versions) and record it as a "keeper" model
4. Given the "keeper" models in 3., we ask the users in question how they want them arranged into a garden
5. Given a confirmed "keeper model", we record its DOI and name in a parsable document (JSON, CSV, etc)
6. Given a user does not respond within a reasonable timeframe (2 weeks?), we publish all unclaimed models to a catch-all garden
7. Given the "keeper" models are migrated to gardens on Garden, they are accessible and runnable

**Comment by WillEngler** [comment]
We identified the working models in this spreadsheet: https://docs.google.com/spreadsheets/d/1BGs5Kn0ymSgHyEIJaFtrkNN8ChGxnO_pdlNe9_8udqs/edit#gid=0

We're migrating all the working models.
