### ISSUE TITLE
Add Authorizer-based Login to GardenClient

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#117]
_Short description_

Native app client thing? Could be run as a native app, put a secret in there, and bypass the full flow in GHA etc.

Enables you to do not just browser based login

Set it up so when you log into garden, you can bring in funcx scopes so you're logging into funcx at the same time.

only difference for user should be that the list of things you're authed for includes funcx

Require consultation with Josh or others (perhaps Eric)

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by ericblau** [comment]
Native App still requires the user to obtain tokens.  Confidential client would allow the client to have its own client ID and secret, but that's not really the right choice for a cli/sdk.  (Also, the client wants to do various things on behalf of the user, not under its own ID--the obvious exception being search ingest.  But I'm happy to discuss this to help flesh out the details

**Comment by WillEngler** [comment]
Small update: @MaxTuecke is implementing a confidential client option for end to end testing in GitHub Action runs. Outside of that I think we're good on our login options.
