### ISSUE TITLE
Create "pitch deck"

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#118]
_Short description_

Create a "pitch deck" for Garden
This should:

Meet people where they are in their understanding, so more of a high level view
Explain the problem Garden solves and how it solves it
Make one deck for the purpose of emailing, and another for the purpose of presenting

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
Closing as stale
