### ISSUE TITLE
Problems installing garden for development

### ISSUE THREAD

**Issue by isaac-darling** [Garden-AI/garden#133]
While attempting to install and use `poetry` with garden, this error was encountered:

```
ImportError while loading conftest 'C:\Users\Isaac Darling\Desktop\Programs\globus\garden\tests\conftest.py'.
tests\conftest.py:9: in <module>
    import garden_ai
garden_ai\__init__.py:1: in <module>
    from ._version import __version__  # noqa  # type: ignore
garden_ai\_version.py:3: in <module>
    __version__ = importlib.metadata.version("garden-ai")
E   importlib.metadata.PackageNotFoundError: No package metadata was found for garden-ai
```

**Comment by isaac-darling** [comment]
1. I am on Python 3.10.8
2. I don't remember for certain, but there was an issue with the `lock` file
3. Both of those commands result in errors

Sorry about the uncertainty with the `poetry install` part but I don't have a record of my command history anywhere.

**Comment by WillEngler** [comment]
I tried switching the Python version I was using for local Garden dev to 3.10 and I hit this issue too. A temporary workaround would be to switch to 3.9. But good to know this seems to repro easily just by using 3.10

**Comment by OwenPriceSkelly** [comment]
that's even more unsettling -- I've been using 3.10 in my dev environment the entire time. maybe there's something going on with local poetry configs?

**Comment by WillEngler** [comment]
Word on the street is that @OwenPriceSkelly got @isaac-darling unblocked on this? If so should we close this?
