### ISSUE TITLE
Bug (sort of): Garden lets you compile and execute pipeline bytecode with different Python versions

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#134]
When registering Pipeline functions on Globus Compute, Garden asks the Globus Compute to serialize the function with its byte code strategy. Let's say a user is using Python 3.10 on their laptop to run the Garden CLI but they are specifying that their Garden use Python 3.8. The pipeline will be serialized as Python 3.10 byte code and the remote container will try its best to execute it with a Python 3.8 interpreter.

A lot of the time that will be fine. But sometimes it could be a big problem. Here's an example from ChatGPT of how that could go wrong:

>As an example, consider the introduction of the LOAD_METHOD and CALL_METHOD bytecode instructions in Python 3.7. These instructions were added to optimize method calls, and code compiled by a Python 3.7 (or newer) interpreter might include these instructions. However, if you tried to run this bytecode on a Python 3.6 interpreter, it wouldn't recognize these instructions, and would raise an error.

> On the other hand, if you took the original source code and ran it directly on the Python 3.6 interpreter, it wouldn't raise an error, because the source code doesn't include any LOAD_METHOD or CALL_METHOD instructions - those are part of the bytecode, not the source code.

I'm not aware of good examples of this in more recent Python versions that we support. For the most part we'd see failures in the case of the user using new syntax that wouldn't have worked even if the source code had been shipped over instead of bytecode. Nevertheless, this is a potential source of mysterious bugs that we could avoid if we figure out how to send over Python code instead of byte code.

# Acceptance Criteria
Given I register a pipeline, when it is registered with Globus Compute, then it is serialized with the source code strategy and not the byte code strategy.

**Comment by Aadit-Ambadkar** [comment]
3.9 bytecode vs 3.11 bytecode
<img width="779" alt="image" src="https://github.com/Garden-AI/garden/assets/58674441/4c7f60c6-ba78-4bfb-8460-13d67766e03f">

the actual code for `btc.py`
```py
import dis
def test(a):
        print(int(a))
        return len(a)

print(dis.dis(test))
```

**Comment by WillEngler** [comment]
Thanks Aadit :) So it looks like PRECALL is an example of an instruction that was added recently that could easily trip us up.

**Comment by Aadit-Ambadkar** [comment]
Yup! and resume.

**Comment by WillEngler** [comment]
Updates on this:
- The original motivation for us to force the bytecode strategy was because our top-level function that is composed of steps couldn't be serialized correctly by the source code strategy.
- I was experimenting with different ways of packaging pipelines that don't do the problematic composition. The source code strategy still fails for simpler pipelines. Assuming we need to include MLflow.pyfunc to use its `load_model` function, the source code serializer chokes on a decorator in the pyfunc source file.
- So unless we figure out how to make the source code serializer play nice with the MLFlow source, we're stuck with the bytecode serializer. (Unless we replace the MLFLow client somehow, which seems unappealing at the moment.)

**Comment by WillEngler** [comment]
Per some of Owen's recent work, we now use the DillCode serialization strategy. So I think this is good to close now? lmk and reopen if I'm mistaken @OwenPriceSkelly
