### ISSUE TITLE
Set up monitoring of Globus Compute endpoint

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#139]
_A good service needs good monitoring! As a User, I want to know that I can publish or run Garden models at any time, without the service going down. As a Developer, I want to save our team time and effort by making robots monitor our services instead of us._

_Add cron jobs, GitHub Actions, etc to monitor the Globus Compute endpoint and ensure that everything is in order (ie credentials are valid, there is enough space on the endpoint server, etc)_

# Assumptions:
1. Globus Compute endpoint for Garden has been established already 
2. Globus Compute endpoint has Kubernetes 
3. We've agreed on what aspects of the endpoint need to be checked periodically, and how often (eg continuously, once a week, upon PR, etc)
4. You are familiar with [cron jobs](https://www.hostinger.com/tutorials/cron-job) and [GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) (GHA) (now is always a good time to learn!)

# Tasks (TBD)
-

# Acceptance Criteria (TBD)
1. Given the Globus Compute endpoint runs out of disk space or RAM, a test/job will fail accordingly
2. Given credentials are invalid or expire, a test/job will fail accordingly
3. ...

**Comment by WillEngler** [comment]
Closing as stale
