### ISSUE TITLE
Move search ingest to a backend route

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#152]
To get ready for wider release, we want to minimize the number of Globus groups we have to add people to. One that we can get rid of is the search group. All our search data is public, so users shouldn't have to belong to a group to query our search index. But you _do_ need to belong to a group in order to write to a search index. (The operation in client.publish_garden_metadata)

If we move search ingest to a backend route and do the ingest operation as Garden, we can avoid that.

# Assumptions:
1.
2.

# Acceptance Criteria
Given I am a user who does not belong to the "Garden Dev Search" group, when I try to publish a garden from my local data.json, then it succeeds.

**Comment by isaac-darling** [comment]
Closed by #177
