### ISSUE TITLE
Refactor steps and pipelines in anticipation of skinny garden

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#168]
- Simplify Step class
- Move validation from steps into pipelines
- Do the starter poetry stuff

Questions to answer:
- Will poetry work for the separate skinny garden package? (hopefully yes)
- Can we cut out Pydantic from the core skinny garden package? (hopefully yes)

@OwenPriceSkelly to fill in the ticket :)

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by OwenPriceSkelly** [comment]
some more story details as I'm thinking through it:
## Assumptions
1. steps (along with models) can move to a module with no intra-garden-sdk dependencies  
2. steps should not need much metadata beyond what is already "baked in" to functions, e.g. `__doc__`/`__name__`
	- pydantic potentially not a dependency for steps anymore? 
3. steps no longer fail to instantiate w/out annotations, but pipelines can fail w/ inconsistent annotations 
4. `mlmodel.py` can be moved to new package, but save refactoring for #169 to the extent possible 

## Acceptance criteria 
1. steps have been refactored to be dumber (enforced?)
2. pipelines are responsible for any "business logic" that currently lives in steps 
3. both questions answered 
	1. clear path to independent sub-package dependency with poetry or investigated alternatives
	2. nothing uploaded to pypi until #169
4. sanity-check a simple inference step in a clean environment with just skinny package installed locally 
5. tests for new/changed behavior 
6. updated docs

**Comment by OwenPriceSkelly** [comment]
obsoleted by #190
