### ISSUE TITLE
Factor out Model class into skinny garden

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#169]
- We need Model download and execution in skinny garden
- Also, needs to tie in new S3 download logic. (Both URL injection and download staging in the remote execution environment)
- Also, can we consolidate down our Model classes? (There are currently 3. Could be 2?)

@OwenPriceSkelly to put meat on the bones.

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by OwenPriceSkelly** [comment]
obsoleted by #190
