### ISSUE TITLE
Per-flavor documentation on serializing models

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#182]
Garden's model registration command makes some assumptions about how ML models have been serialized. For example, we assume that Scikit-learn models are serialized with pickle. This is probably common, but [the docs](https://scikit-learn.org/stable/model_persistence.html#python-specific-serialization) show a number of options. 

We should ...
1. Take a second pass on how we're ingesting models and make sure we're covering common cases that users would expect.
2. Add a section to [the docs](https://garden-ai.readthedocs.io/en/latest/user_guide/tutorial/) with example code on how to serialize models in all the flavors we support.

# Assumptions:
1.
3.

# Acceptance Criteria
Given I am a Garden publisher, when I have finished my model training and am looking for boilerplate on how to export my model in a way that will work for Garden, then I can turn to the docs and see exactly how to do so.

**Comment by steve-barnard** [comment]
Closing out per quick check with Will.
