### ISSUE TITLE
Basic unit testing for garden backend app

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#184]
Currently the backend app does not have any unit tests, let alone unit tests that run on PRs. Set this up and make a basic set of tests that cover all our routes.

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by Aadit-Ambadkar** [comment]
Should the tests create a fake garden and then verify its usability? If so, how would they delete the test garden after use (to prevent to many unusable gardens from being clogged up)
