### ISSUE TITLE
Allow creation of steps in the interpreter

### ISSUE THREAD

**Issue by isaac-darling** [Garden-AI/garden#186]
As it stands, validation fails when making a step in the terminal interpreter because the source for the step cannot be found.

# Assumptions:
1. User uses the step decorator to define a step in the terminal interpreter

# Acceptance Criteria
Given a user who wants to make a step in the terminal, when they attempt to do so, then there is no `ValidationError` and the operation is successful.

**Comment by WillEngler** [comment]
Closing stale tickets today. This isn't an issue anymore AFAIK
