### ISSUE TITLE
BUG: import naming error

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [Garden-AI/garden#188]
Installing garden-ai on a clean environment installs globus_compute_sdk 2.2.1. However, garden-ai depends on globus_compute_sdk 2.1.0. This causes a pretty significant problem:

In globus_compute_sdk 2.1.0, the Serializer Error class is:
```
class SerializerError:
    def __init__(self, reason):
        self.reason = reason

    def __repr__(self):
        return f"Serialization failed due to {self.reason}"
```

In globus_compute_sdk 2.2.1, the Serializer Error class is:
```
class SerializationError(Exception):
    def __init__(self, reason):
        self.reason = reason

    def __repr__(self):
        return f"Serialization failed due to {self.reason}"
```

See the git blame here: https://github.com/funcx-faas/funcX/commit/821234d1bb39fdc73975d01ffda18e3bf1daac32

The small difference between `SerializerError` and `SerializationError` causes an import error in the funcx bandaid which prevents the cli from working entirely.

2 possible fixes:
1. require globus_compute_sdk to be 2.1.0
2. require globus_compute_sdk to be 2.2.0 or greater, and change Serializer to Serialization

I am in favor of option 2, because it looks like the change will stay permanently

**Comment by WillEngler** [comment]
Resolved for now by #189 which pinned the globus-compute-sdk = "2.1.0". When we are ready to specify our serializer we can bump to the latest version and take off the bandaid
