### ISSUE TITLE
Try uploading one of Rafa's models

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#201]
Step 1: obtain a GitHub repo and/or notebook from Rafael with a pretrained model and supporting code.
Step 2: try to upload it

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
Rafa suggests starting with one of these:
- https://github.com/learningmatter-mit/GenZProt
- https://github.com/learningmatter-mit/peptimizer
- https://github.com/learningmatter-mit/Chem-prop-pred

**Comment by ascourtas** [comment]
I can't remember, has this been completed yet?

**Comment by WillEngler** [comment]
Nope. I'm actively working on it, and hope to be done tonight or tomorrow.
