### ISSUE TITLE
Mentors: Decide on metadata additions

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#204]
_Short description_

Chase has identified metadata that's potentially important for effective FE displays. Meet ASAP to decide on this so we can unblock Chase

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
I dropped some thoughts in #210. tl;dr; I think Chase should go at it and add whatever he wants within reason. (And all the fields he suggested are within reason.) And imo he should just get a draft of it down and we can go from there. Happy to meet and discuss more if we want but by default I'd just give him the green light async.

**Comment by WillEngler** [comment]
Gonna close in favor of #210 (Chase is good to implement)
