### ISSUE TITLE
bump pydantic to 2.x 

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#228]
pydantic v2 is out - among other things, the support for computed properties w validation looks nice, probably some other stuff too.  

migration guide: https://docs.pydantic.dev/latest/migration/

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
And convert the property setters in ModelMetadata.__init__ to real computed properties while we're at it

**Comment by WillEngler** [comment]
Marking as blocked because there's not much we can do with the Globus Compute dependency pinned to < 2

**Comment by WillEngler** [comment]
Closing as stale - not actionable rn

**Comment by OwenPriceSkelly** [comment]
globus compute relaxed their pydantic constraint, so we're free to (finally) migrate to pydantic 2.x
