### ISSUE TITLE
Add authors and affiliations to Garden

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#23]
_As a Garden Publisher I want to be able to add authors' affiliations to garden metadata_

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by OwenPriceSkelly** [comment]
current representation of garden authors is just a list of strings, so we'll need to decide if author-specific metadata should be represented as an `Author` class with name and affiliations as attributes, or if we just want something simpler like a `garden.affiliations` dictionary with names as keys

**Comment by OwenPriceSkelly** [comment]
my vote is simple dictionary, unless there are enough other author-specific metadata fields to make that unwieldy

**Comment by WillEngler** [comment]
We've added authors along the way and I think this ticket is stale now. I move to close this ticket.
