### ISSUE TITLE
Add Pipelines to a Garden

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#24]
_Short description_

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by OwenPriceSkelly** [comment]
_As a Garden author/owner with some set of pipelines (possibly from different
authors) to incorporate in my Garden, I want (a) each pipeline's steps to be
validated for internal consistency (w/r/t input and return type annotations)
and (b) my Garden's metadata to be updated to reflect the added pipelines and
their respective contributors._


# Assumptions

1.  pipeline metadata will include attributes for title, authors, contributors, steps, and a doi
2.  Steps will include attributes for title, authors, contributors, and a doi
3.  Authors of a pipeline or step automatically are considered &ldquo;contributors&rdquo; at the Garden level
4.  Steps will be any callables; Pipeline `__call__`&rsquo;s will entail calling the steps in the correct order
5.  Story ends when correct pipeline metadata is also written with the rest of the garden metadata


# Acceptance Criteria

1.  Good case:
    -   Given: an instantiated garden and a list of callable Steps
    -   When: invoking &ldquo;build\_pipeline(steplist)&rdquo;
    -   Then: garden should build a pipeline consisting of those steps (and validate the function signatures)
    -   Then: garden metadata should recognize pipeline or step authors as contributors
2.  Bad case:
    -   Given: an instantiated garden and a list of steps, some of which are not callable
    -   When: invoking &ldquo;build\_pipeline(steplist)&rdquo;
    -   Then: garden should indicate the problematic steps to the user, without modifying the existing garden
