### ISSUE TITLE
Ecosystem analysis: How are people building reproducible containers for science?

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#266]
A lot of Garden publishing difficulties boil down to, how can a user get a model running on their workstation and then package up their code and environment such that they are confident it will work somewhere else? We are far from the only team facing this problem. This ticket is for tracking some exploratory analysis on how other projects approach this problem, and what good ideas are out there that we could adopt.

Some examples:
- https://github.com/conda-incubator/conda-store
- https://github.com/replicate/cog#why-are-we-building-this

And a discussion on the Python forums about this:
https://discuss.python.org/t/user-story-to-consider-for-dependency-specifications-reproducible-science/

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by steve-barnard** [comment]
Your links cover a decent amount on the subject.

This somewhat dated post encompasses the [data storage aspect.](https://mattermodeling.stackexchange.com/a/325)

This also might be worth mentioning [Posit's curated PyPi] (https://docs.posit.co/rspm/admin/python-packaging/curated-pypi/) after reading the discussions on the python forums.

Leaving this comment here for now and continuing to look around.

**Comment by steve-barnard** [comment]
I recall discussing apptianers, again dropping useful links here:
- https://insidehpc.com/2019/02/argonne-looks-to-singularity-for-hpc-code-portability
- https://insidehpc.com/category/news-analysis/

The following may seem a bit of a ramble howeverm I'm also curious about a few other items as it relates to the specific use cases for HPC with garden.

- Will garden always point to the same HPC system (globus compute)?
- How are jobs submitted to be run (what does this process look like currently)?
- What is preventing us from creating a bulky container/apptainer (think a default apptainer image in a .sif that can be pulled and used for everyone, and if needed provide the user the ability to add extra installs for their workflows)?
    - have the same default directories for data etc mounted 
- Do we expect users to submit a test job/garden or do we build a method to allow this?
- Is there any reason we wouldn't want to use Anaconda/conda/miniconda with a conda environment file?
    - apptainer with mini conda and an environment file along with activating the env to then run the code.
    - possibly able to leverage the .sif format to save off apptainers for reproducibility & Sharing
    
- Have there been any updates or thoughts from the team on this since I've last spoken with you @WillEngler ?

**Comment by WillEngler** [comment]
Sorry I fell off on this 🤦 

> Will garden always point to the same HPC system (globus compute)?

For now we only have plans to use Globus Compute to run functions. That said, we do intend to take advantage of Globus Compute to run across multiple HPC clusters.

> How are jobs submitted to be run (what does this process look like currently)?

In short, like this

```
        with globus_compute_sdk.Executor(endpoint_id=str(endpoint)) as gce:
                future = gce.submit_to_registered_function(
                    function_id=str(self.func_uuid), args=args, kwargs=kwargs
                )
                return future.result()
```

So right now we submit one job per Garden pipeline invocation.

> What is preventing us from creating a bulky container/apptainer (think a default apptainer image in a .sif that can be pulled and used for everyone, and if needed provide the user the ability to add extra installs for their workflows)?

This is basically the direction we're going. We think we want to provide different "flavors" of base images with, eg, different Python versions pre-installed. And eventually, probably different versions of CUDA and such too. Check out #317 that just landed.

> have the same default directories for data etc mounted

That said we're starting out with the basics, so we don't have things like that yet, which could be nice!

> Do we expect users to submit a test job/garden or do we build a method to allow this?

I don't think I understand this question. I do think users will kick the tires on newly submitted pipelines and that's well and good. But I don't think we have plans for any "test" version of Gardens or other objects in our system. Can you give me more color on this?

> Is there any reason we wouldn't want to use Anaconda/conda/miniconda with a conda environment file?

For the first draft of the system this is not far what we did. (The ContainerSpec is not far from a conda env file, and repo2docker goes and creates a conda env under the hood with it IIRC.)  One reason we're moving away from it is that it doesn't accommodate all of our test cases. (See #237 for example.) For that and to accommodate more general env setup, we're moving towards "environment definition scripts" - arbitrary code the user can write to define their container. In full generality this means they can write their own Dockerfile/Apptainer spec. But right now we're experimenting with a notebook-driven flow as our first stab at it.

> Have there been any updates ...

Haha yes, sorry. We should catch up soon! I will follow up in Slack.

**Comment by WillEngler** [comment]
Closing as stale. Steve brought in some useful research. Now we're on a pretty different tack with the new publishing process
