### ISSUE TITLE
dogfood with ptychoNN 

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#268]
after talking with Jim in a bit more detail, I think ptychoNN would be a great dogfooding candidate in the not-too-distant future (especially when we get closer to whatever `vFAIR-score` is going to look like, I think there might be some cool "bespoke validation" use cases it could help motivate)

**Comment by OwenPriceSkelly** [comment]
fleshing out some notes:
I don't think that dogfooding ptychoNN in the current version of garden would yield any novel insights/gripes, and it would be a ton of work to get into seedling shape. Still, I think we should plan to revisit the model eventually as a motivating case when it's time to start thinking harder about (a) model/dataset versioning and (b) validation/fair-scoring/etc that's more sophisticated than "give us some sample inputs and outputs, please"

my understanding of the real-life ptychoNN use case is:
  - user scientist gets some unprocessed ptycho-data running an APS experiment
  - there's a computationally expensive non-ML process to get "ground truth" results from that data
  - ptychoNN inference is mostly useful in real time as a first approximation, while the experiment is still running. 
  - (cool part) once the slow results come in, they become part of the ground truth used to (re-)train the model 

I think this will eventually make an interesting case for a couple reasons. One is that this is the first real use case where it seems to me like it makes more sense for an updated pipeline and associated dataset to keep their same respective DOIs as they update than it does to collect and reference older versions with unique DOIs. 

I also think this could be an interesting case in maybe the same vein as our wisconsin collaborator's automatic error bars concept -- whatever `vFAIR-score` looks like, this makes me think it would maybe want to be agnostic enough to be able to integrate with some pretty bespoke validation metrics

**Comment by ascourtas** [comment]
I'm not adding this to the current Dogfooding Milestone since it's posited as a potential future event :)

**Comment by WillEngler** [comment]
Closing as stale
