### ISSUE TITLE
Reach out to community for partnerships and dogfooding opportunities

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#269]
_As a Developer and Product Owner, I want to establish relationships within the community early on to get Garden cold-started_

We want to know what the community wants and needs, and if Garden in it's current vLogan form will work for those needs

Reach out to a few different groups (ex: ANL CELS) and see if anyone is interested in providing work/models for us to publish as part of our Garden dogfooding push. 

# Assumptions:
1. We are able to reach out to communities that encapsulate all of our potential publishers (see [Garden User Personas](https://miro.com/app/board/uXjVOxpxyXY=/?moveToWidget=3458764533991665768&cot=14))

# Acceptance Criteria
1. Given discussions with potential partners were established, those discussions are captured in documents linked here with clear next steps

# Tasks

- [ ] Reach out to ANL folks
- [ ] ....

**Comment by WillEngler** [comment]
I'm content with the models we have for dogfooding and I think the set we have covers the bases of the personas in Miro.

**Comment by ascourtas** [comment]
I assume this is done? @OwenPriceSkelly can you add links to the conversation notes you had?

**Comment by OwenPriceSkelly** [comment]
conversation notes here! #268

**Comment by ascourtas** [comment]
closing unless someone tells me otherwise
