### ISSUE TITLE
Assess dogfooding results

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#270]
_As a Developer and Product Owner, we want to compile what we've learned from the dogfooding process in a way that is easy for the full team to understand, such that we can make any necessary changes to Garden if necessary_

The dogfooding push has been hard fought, and now it's time to assess where we stand! What was good? What was bad? What needs to change? 

Create a report to show to the team for discussion and any necessary decision-making. 

# Assumptions:
1. We've done enough dogfooding thus far to assess (see other issues in Dogfooding Milestone)

# Acceptance Criteria
1. Given the report/s, the team is able to understand the problems and some potential solutions fully.

# Tasks

- [x] Create problems doc
- [x] Create solutions doc

**Comment by WillEngler** [comment]
Love to see a ticket get tagged to me and then it's already done 😎
