### ISSUE TITLE
Make Garden poster for NSF CSSI Meeting

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#273]
We need a Garden poster ready to print in Houston on September 26. https://www.cssi-pi2023.org/posters

# Assumptions:
1.
2.

# Acceptance Criteria
Given Will is in beautiful Houston Texas, when he rolls up, then he has a beautiful poster to show.

**Comment by ascourtas** [comment]
I assume this is still in progress? Bumping to Sprint 18

**Comment by WillEngler** [comment]
Correct!

**Comment by WillEngler** [comment]
Poster is done now. Uploaded to Figshare per NSF request and submitted. DOI is 10.6084/m9.figshare.24213060.

Physical copy is in Madison because Ryan Jacobs had a travel tube and I didn't :) 

PPTX for future edits is in "External Presentations" folder in shared Garden drive.



[garden_cssi_poster.pdf](https://github.com/Garden-AI/garden/files/12751717/garden_cssi_poster.pdf)
