### ISSUE TITLE
Rewrite install docs to make them less pipx-centric

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#276]
Our installation docs currently recommend using pipx to install and use garden. This is fine for some CLI operations, but you generally need to install garden-ai in a venv so that you can import it and other libraries together in a pipeline file that you're working on. We should change our install recommendations to reflect this.

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by ascourtas** [comment]
During my trial, even with using a Conda virtual environment `pipx` was still untenable when installed via `brew`. The solution was uninstalling it from `brew` and installing it with `pip`. More details here: https://docs.google.com/document/d/1xdTy3KZgt0U6rixDcW8YYcPXhyad1qErJ4A_lqT1l_c/edit#heading=h.m1v24wjgt8se

**Comment by WillEngler** [comment]
I think we erred in suggesting pipx at all. I'd recommend that publishers don't use pipx and instead use a "normal" venv.
