### ISSUE TITLE
disallow `Any` annotations

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#28]
# disallow `Any` annotations

*as the author of a step, I might be tempted to label argument/return
types as the `typing.Any` type. This is not a good idea for steps, and I
should not be allowed to do that.*

The `Any` type only exists in the first place as a way to soften the
type-hint-adoption curve, which is counter to the point of our requiring
them for steps in the first place. Moreover, because the future of
python type-hinting is pretty shaky, we're likely going to need to
repair/reimplement our `issubtype` helper and limiting the set of
annotations we're willing to accept would simplify that in the future.

## Acceptance Criteria

- Given: `Any` in a step's annotation
- When: validating the step
- Then: user should be politely advised to do better

## Assumptions:

- if users can opt-out of annotation checking implicitly (by using `Any` for an annotation), they should also be allowed to do so explicitly (e.g. a `@step(check_type_hints=False, author=...)` kwarg to opt-out)
- implicitly/explicitly opting out should entail the same behavior under the hood

**Comment by WardLT** [comment]
Are we doing to issue a warning, or is this going to be a error that prevents publication?

**Comment by OwenPriceSkelly** [comment]
I think that we should treat it the same as opting to not annotate -- if users should be allowed to opt out of annotation checking/ "safe" step composition (which might be wise since annotations seem brittle), then use of `Any` in annotations seems like it could be treated same as opting out. Even if we did decide to disallow them, users could just label with `object` for (afaik) the same effect

**Comment by OwenPriceSkelly** [comment]
Thoughts on this as I'm working: I have a hunch that the classic `AttributeError: '{obj}' has no attribute '{name}' error is going to be _extra_ annoying if it's happening mid-pipeline, in a docker container, on a funcx endpoint, etc; when the actual objects being manipulated are domain-specific this seems extra plausible. 

IMO the best way to deal with that family of errors is with a little red underline in the user's IDE, which mypy or whatever is going to do automatically when it sees the non-`Any` type hints we're making the user write out. 

I'm imagining the following: new Gardener has e.g. a jupyter notebook with the code they'd like to turn into a garden pipeline, so they write some steps like: 
``` python
@step
def f(data: pd.DataFrame) -> DomainSpecificType:
    # copy-pasted contents of a cell as function body
    return fancy_object_with_specific_attribute
@step
def g(fancy_object: Any):
    do_something(fancy_object.typo_in_specific_attribute_name)
    # ^^ user typo is invisible and causes problems even later than usual 

# contrast with: 
@step
def g(fancy_object: DomainSpecificType):
    do_something(fancy_object.typo_in_specific_attribute_name)
    # ^^ mypy/IDE tells the user about the typo so we don't have to
```

I think this justifies being sticklers about `Any`, so I'm adding a validator to steps which checks for `Any` specifically

**Comment by WardLT** [comment]
I'm for checking `Any`, but can I suggest adding an option to avoid this type check and still publish? Or, at least designing in a way such a check could be avoid. I'd hate for people to spend too much time debugging type annotations for the intermediate steps of a workflow

**Comment by OwenPriceSkelly** [comment]
Yeah I can see that, definitely adds some friction to the experience of developing a pipeline, but I think I want to push back a little: opting out is only going to save you at most 1 (publication-time) exception per step, and we can make that exception as friendly and useful as possible. On the other hand, opting out comes at the (admittedly speculative) cost of hiding a pretty common flavor of bug until runtime, which seems to me like it would amount to much more friction for both the user and whichever one of us is helping them find the logs of the model they published x weeks ago, etc etc. Plus the stacktrace is likely to look totally opaque when the exception happened in a method called `pipeline._composed_steps()` that the user has never seen before, and worst-case (again speculative) scenario, we can't even pinpoint which step is the problem, which seems worth trying our/their hardest to avoid. 

Especially if it is the case in practice that most pipelines are only 3-4 steps, I'm not sure it'll even be that much inconvenience for users. 

one possible compromise: to disallow `Any` altogether in favor of allowing basically identical behavior in a deliberately inconvenient way ("path of most resistance") is to make sure that `arg: object` is treated as valid, so if someone really on-purpose doesn't want the sanity check they can sneak by; this has the upshot of (I think, depends on the IDE) allowing a user to publish a pipeline sans informative annotations, but only if they're willing to look at a bunch of red squiggles in their ide every time mypy sees them trying to access an attribute on `arg` that doesn't exist on a bare `object`

**Comment by WardLT** [comment]
I think the `arg: object` is a good compromise, though it doesn't feel strikingly different than someone intentionally annotating "Any." Is "Any" the default type assigned to an argument? 

Thinking more about why I'm worried about this, it's because of Python's duck typing making it possible for "any" object to work in a function regardless of it actually being the correct type. This may appear more often than we'd like with Python lists, numpy arrays, and TF objects all being acceptable inputs to some libraries.

**Comment by WardLT** [comment]
I'd like like an ability to let Garden reflect that types in Python are just illusions 🧙🏼

**Comment by OwenPriceSkelly** [comment]
Ok I think I'm on the same page here -- I actually like `object` much better than `Any` because it's true to the actual python data model, the arguments **are** always going to be objects, while `Any` is only there to signal to static type checkers that you'd like them to be quiet -- `isinstance(None, object) == True`, but `isinstance(None, Any)` is `TypeError: typing.Any cannot be used with isinstance()`

**Comment by WardLT** [comment]
Nice! I didn't know about that behavior of `Any`

Ok, I'm on team "object"

**Comment by OwenPriceSkelly** [comment]
racking my brain for a "no objections" joke here
