### ISSUE TITLE
Diagnose garden-ai CLI startup time. Make garden-ai --version execute instantly.

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#280]
In some exploratory testing, Ari found that running `garden-ai --version` took 15 seconds. That is a lot!!! Just now I tried it and it took a few seconds. (But then running it more times went more quickly.) What's going on here? We'd like simple commands like this to execute instantly.

# Assumptions:
1.
2.

# Acceptance Criteria
Given I am a CLI user, when I run garden-ai --version, then it executes almost instantly.

**Comment by isaac-darling** [comment]
after some extensive testing, I have discovered that the cause of the slow startup (caching) is dependent on ANY import that touches the `garden_ai` namespace (if that happens, Python appears to walk the entire tree and cache everything). I was able to write a short script and add a line to the `pyproject.toml` that allows `garden-ai --version` to run instantly, but of course it relies on the script being outside of the `garden-ai` namespace, which I am unsure we can replicate for users.

When `garden-ai` is installed through `pip` it appears to add an executable to the Python installation's root dir/Scripts, and if indeed we get to specify the code for this binary then I can solve the issue. Alternatively, if it is known where and how the binary is generated, then I might be able to find a way to finagle its definition with the above restriction.
(copied from Slack)
