### ISSUE TITLE
Make garden-ai point to production by default, including production DataCite account

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#284]
_We need to make sure that our dev/prod environments use the corresponding datacite test/production endpoints to generate or update dois_
Related to #154 and #119 
# Assumptions:
1. We have the prefix, account ID, and password for production DataCite in aws secrets
2. Backend terraform has been configured to grant secrets access to dev/prod requests appropriately 

# Acceptance Criteria
Given: Some metadata and a request for a DOI
When: hitting the garden dev api
Then: datacite test endpoint generates the doi

When: hitting the garden prod api
Then: real datacite generates the doi

**Comment by OwenPriceSkelly** [comment]
update: all that's "blocking" this is putting the real datacite creds in aws secrets (the backend code is already in place), we've just decided we're not actually at the point of needing/wanting real DOIs quite yet

**Comment by ascourtas** [comment]
TODO: add this to a README somewhere so it's documented and we can closet this issue
