### ISSUE TITLE
write more readable json

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#29]
# write more readable json

*As the author of a Garden, I'm habitually setting `year = "2022"` on
all of my gardens, even though it's now 2023. The generated
metadata.json should be as human-readable as possible, so that I (or
someone helping me debug) could spot this sort of mistake at a glance*

This is probably as easy as pretty-printing the json we write to the
metadata file, but there might be json fields which are likely to be of
particular human interest or which are especially typo-prone; we might
want to reorder those fields to appear towards the top of the file.

## Acceptance Criteria

- Given: a complete/valid but incorrect metadata.json generated for a
  Garden
- When: viewing that file
- Then: the contents should be as human-readable as possible while still being json

**Comment by blaiszik** [comment]
`repr_html()` is an interesting way to surface the most interesting fields for users in Jupyter

**Comment by OwenPriceSkelly** [comment]
https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display

**Comment by OwenPriceSkelly** [comment]
with the CLI, we'll be able to get pretty json by passing the `--verbose` flag
