### ISSUE TITLE
Pipeline Metadata Design Update

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden#294]
_Short description_
As a consumer, I want there to be information about the pipeline so I can understand if it meets my needs.
As a publisher, I want to attach the metadata for my pipeline to my notebook so consumers can understand if it meets their needs.

# Assumptions:
1. Deliverable will be an update to the existing pipeline pydantic class
2. Use frontend designs in Figma for additional metadata fields
3. The schema is documented in the Garden documentation website

# Acceptance Criteria

Given I am on the Garden docs, when I click on `metadata schema`, then I see the correct metadata schema in an easy to understand format.

**Comment by WillEngler** [comment]
Superseded by #314 and new metadata design-specific ticket that we are about to write

**Comment by WillEngler** [comment]
Merged #330 and #326 with updates on models, datasets, and pipelines that I'd sketched out in the FE mocks (https://github.com/Garden-AI/garden-frontend/pull/58). Here's the current readthedocs for the Pipeline class: https://garden-ai.readthedocs.io/en/latest/Pipelines/

There's gonna be follow-up work to pipe all the data end to end, but I think we've hit the mark on updating the metadata design.

**Comment by WillEngler** [comment]
Had some good follow-up conversations where we hashed out more details on the metadata. Basically we're good with the format worked out in the PRs I got in, plus the re-addition of steps. Going to mark this design phase of work as done. There are now more targeted tickets for getting the metadata flowing end to end: #334, #339, https://github.com/Garden-AI/garden-frontend/issues/61
