### ISSUE TITLE
Submitting a Pipeline for Publication

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden#295]
_Short description_
As a publisher, I want to publish my pipeline using my notebook so it can be on Garden.
# Assumptions:
1. This does not publish the pipeline to the website

# Acceptance Criteria

Given I have a complete publishing notebook, when I type `garden-ai publish file_name.pynb`, then I can see my pipeline in my Garden locally with `garden-ai list`.

Given I have a notebook with a failure in it, when I type `garden-ai publish file_name.pynb`, then I get a useful error message.

Given I have a notebook without a pipeline in it, when I type `garden-ai publish file_name.pynb`, then I get a useful error message.

**Comment by WillEngler** [comment]
Superseded by #314
