### ISSUE TITLE
HPC capabilities

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden#296]
_Short description_
As a consumer, I want to do my inference on an HPC, so I can use the resources NSF gave me.
# Assumptions:
1. Globus compute apptainer build process exists
2. We have a demo endpoint
3. This happens at publish time on the demo endpoint
4. The user tested the pipeline with their local docker 

# Acceptance Criteria

Given I have a valid pipeline to publish, when I publish to the garden, then I can run my pipeline on the demo endpoint.
Given I have a valid pipeline to publish and the demo endpoint is down, when I publish to the garden, then I get a useful error message.

**Comment by WillEngler** [comment]
Closing as stale
