### ISSUE TITLE
metadata sync should be harder to skip

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#30]
# metadata sync should be harder to skip

*as a Gardener whose garden will use steps/pipelines with their own metadata,
such as authors/contributors, it should be impossible (or at least more
difficult) to generate metadata.json that is outdated w/r/t the actual `Garden`
object's attributes*

The reason it seems pretty easy currently to miss this is because the
implementation of  `register_metadata(garden)` (and/or the call to
`garden.validate()` that it wraps) assumes that the user is doing so because
they've finished modifying their garden – i.e. it's the final step before the
garden is "publication ready". However, one might instead assume that their
garden should be registered and validated as soon as they're done with the
garden-specific metadata, *before* the pipelines are included.
Redundant/out-of-order calls to `register_metadata` or `validate` are totally
fine if there's at least one at the end of the process, too.

One way this specific case could have been addressed is just by issuing a
warning when trying to register a garden without pipelines, not throwing an
exception, but that might still be too easy to miss/ignore.

We could also add a "validator" to Gardens that tries to update any metadata
it's already written whenever the Garden is modified, which is a stronger
guarantee but feels messy

We also might just make it extra clear in documentation that the
`register_metadata` step ought to be the last step, and leave it at that,
mountains out of molehills etc

## Example:

From slack conversation [here](https://garden-j9u4076.slack.com/archives/C0462JYUWTV/p1671658841098769) about Ben G's demo, it was 
pretty easy to accidentally generate incomplete json by writing the garden's
metadata (by calling `register_garden`) too early, before any pipelines had been
added.

``` python
# Intuitive step 1: initialize garden/set some attributes
garden = client.create_garden(authors=['Ward, Logan'],
                              title="Composition featurizer of Ward et al. 2016",)
garden.description = "Formation enthalpy predictor"
...

# An intuitive but incorrect step 2: register the garden, now that
# garden-specific attributes are done (should be one of the very last
# lines in the file)
client.register_metadata(garden)

# ^ this isn't something we need to discourage, either -- the more the
# user validates the contents of their garden the better, imo


# defining steps/pipeline is ok either before or after the Garden (since they
# may have been imported from another module, or borrowed from another garden
# entirely)
@step
def parse_compositions(formulas: list[str]) -> list[Composition]:
    return [Composition(x) for x in formulas]
...
predictor_pipeline = Pipeline(
    title="Formation enthalpy predictor from molecule compositions",
    steps=(parse_compositions, featurize_composition, predict),
    authors=garden.authors,
)

# (!) problem: this updates the necessary attributes on the garden object, but does not write an updated metadata.json
garden.pipelines = [predictor_pipeline]

# if registered/written *after* the inclusion of the pipeline, the metadata looks correct
# client.register_metadata(garden)
```

## Acceptance Criteria

- Given:
- When:
- Then:

**Comment by blaiszik** [comment]
I like the idea of tackling this with improved documentation at this point.

We could also consider changing the name of `register_metadata` to something that is more final sounding
e.g., `client.publish(garden)` would probably make it feel awkward for someone to write anywhere but the end

**Comment by OwenPriceSkelly** [comment]
I agree, I think renaming the method to `publish` and adding a warning for the obviously non-final case of an empty garden is probably enough for this story

**Comment by WillEngler** [comment]
Superseded by new "create garden" story
