### ISSUE TITLE
implement helper to run pipelines

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#31]
# implement helper to run pipelines

*when visiting someone else's `Garden` with pipelines I'm interested 
in calling, I should not need to directly touch their Garden's
`garden.pipelines` attribute, (which is currently just a list of 
pipeline objects) in order to call the pipelines.*

That is, I would much prefer something like:

``` python
results = someones_garden.run_pipelines(
    {"Friendly Pipeline Name": my_pipeline_input, 
    "10.26311/other-pipeline-doi": other_input}
)
```

vs something like:

``` python
results = someones_garden.pipelines[2](my_pipeline_input), someones_garden.pipelines[0](other_input)
```

I have a hunch I would also find it especially convenient if the 
interface supported running the same pipeline in parallel from a set
 of inputs and collected their respective outputs for the sake of 
comparison. (This might make the "preferable" interface impossible 
with just a dictionary, but a list of `(pipeline_key,input_val)` 
tuples would maybe be fine in that case?

This seems like it could accidentally become a pretty big story, and
maybe even one we shouldn't move forward with until we've got some
feedback from the user survey

Edit: this should wait at least until we've made up our minds w/r/t using MLflow 

## Assumptions:

1.  
2.  

## Acceptance Criteria

- Given: A Garden containing pipelines but no direct access to those pipeline objects 
- When: I call `run_pipelines` with the appropriate arguments
- Then: the `Garden` object can invoke the pipelines I specified for me, possibly in parallel, and collect their results.

**Comment by BenGalewsky** [comment]
Obsolete now
