### ISSUE TITLE
Bug: Docker client failing to create

### ISSUE THREAD

**Issue by MaxTuecke** [Garden-AI/garden#318]
When running `garden-ai notebook create`, `docker.from_env()` will raise the exception:
`DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))` 
if docker has 'Settings>Advanced>Allow the default Docker socket to be used' turned off. 

This issue does not happen if all docker commands are just run with subprocesses.

**Comment by WillEngler** [comment]
Blech, thanks for the heads up. Googling around, it looks like this Docker Desktop change surprised a lot of dev tools that build on top of Docker. Let's keep an eye on this

**Comment by WillEngler** [comment]
Added warning about this in Docker troubleshooting docs
