### ISSUE TITLE
`garden-ai setup` command 

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#321]
The new publishing flow relies on some assumptions about the user's local docker install that might require a little bit of extra configuration on their end. 

Specifically, we need docker desktop to be installed, the docker client to be able to instantiate (see #318) and the user to have push access to a public docker hub repository where we can store their images. This command should verify both and prompt the user with a fix if it can't. 

It could also store the name of the docker hub repository in local_data (like with their email) so the user doesn't need to specify it each time they register their notebook

**Comment by isaac-darling** [comment]
With other upcoming changes (Max's work with ECR) this functionality is no longer needed.
