### ISSUE TITLE
`@pipeline_test` decorator

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#342]
If we had a way for users to explicitly define a test function which calls a given pipeline, we could use that to collect metadata like type signatures about the pipeline as well as automatically test remote inference / assign FAIR scores etc 

Not a priority currently, just getting this idea up for posterity

**Comment by WillEngler** [comment]
I think the first draft of this would look like ...
- Let users tag a function as a @pipeline_test (or @entrypoint_example or what have you)
- Include that as metadata on the pipeline.
- Tweak the frontend to include the example function where there is currently generic code showing how to invoke the pipeline
