### ISSUE TITLE
Prevent accidental dill slippage

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#357]
The DLHub endpoint assumes that pipelines have been serialized with dill 0.3.5.1. We bake that version of dill into our base images. But what if someone installs a library with a different (later) version of dill? Then remote deserialization will probably fail.

At minimum ...
- Lock the dill version in Garden's dependencies to 0.3.5.1.

And maybe ...
- Add some check or failsafe in the publication process that aborts publication if the publication process is running with the wrong version of Dill

# Assumptions:
1.
2.

# Acceptance Criteria
Given I am a Garden publisher, when I publish my notebook, then there is no way that it gets serialized with a version of Dill that the River worker can't deserialize.

**Comment by OwenPriceSkelly** [comment]
https://github.com/uqfoundation/dill/issues/609
