### ISSUE TITLE
rebrand `Pipelines` -> `Entrypoints` 

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#358]
Out with the old. The objects-formerly-known-as pipelines are going to become something else, tentatively `Entrypoint`s as of Owen and KJ syncing on 12/4. 

`Pipeline`s as a concept still exist as the special case of an `Entrypoint` (or whatever) that actually _does_ consist of multiple steps in a sequence 

(will's recap copied from slack): 
> Gardens are a collection of entrypoints. Entrypoints have at least one step. If entrypoints have more than one step, we consider them pipelines.

> At a technical level, we're good to change PipelineMetadata to EntrypointMetadata on the backend. (And similar for other occurrences of "pipeline") And that will be reflected in the serialized metadata in Globus Search. (Gardens will have lists of `entrypoint`s.) The decorator in the notebooks will be `@garden_entrypoint`. Entrypoints will still have lists of steps. As now, they'll always have at least one step. (The `@garden_entrypoint` function). And as now, the publisher can add more steps with `@garden_step`.

**Comment by kjschmidt913** [comment]
a one-step pipeline becomes an entrypoint. Pipelines still exist as workflows (lol needed another word) with multiple steps
