### ISSUE TITLE
See if we can simplify or remove the GardenFileAdapter

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#364]
A while back, Max found a clever way to work around Globus Compute needing a separate native app login from the GardenClient: https://github.com/Garden-AI/garden/pull/225. This was probably a common enough problem that the Compute team has addressed it. Per their v2.7 release notes on Nov 8 ,

> Added a new AuthorizerLoginManager to create a login_manager from existing tokens. This removes the need to implement a custom login manager to create a client from authorizers.

So we might not need the custom solution any longer, which would be great.

# Assumptions:
1. Whatever we do shouldn't take away the ability to log in during automated test runs from GitHub Actions. (ie, make sure we stil support ConfidentialAppAuthClient)
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by MaxTuecke** [comment]
For the present, it looks like we still need the garden file adapter. To avoid the double login issue, the compute executor in ```entrypoints.py``` requires that either compute's authorization tokens be stored in compute's file system or for an authorized compute client to be passed into the executor. The garden file adapter is currently storing the authorization tokens with both garden and compute. Until compute has a better way to force token storage, this still seems to be the best solution.
