### ISSUE TITLE
`garden-ai purge` to get rid of any local Docker artifacts created/pulled by Garden

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#366]
Because Garden goes and runs Docker commands on behalf of the user, they will end up with cruft images eventually. There should be a command that removes any Docker images and containers created or pulled by Garden. That way the user doesn't have to fumble around with docker commands to reclaim disk space.

`garden-ai weed` might be fun too 🤔 

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by ascourtas** [comment]
may need to rethink component
