### ISSUE TITLE
Hello, Model Registry

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#37]
_As a garden user I want a registry to publish my models to and read from_

# Assumptions:
1. Will be a deployment of MLFlow tracking server on ECS behind an ALB using OAuth2 proxy. See [this article](https://getindata.com/blog/deploying-secure-mlfow-aws/) for details.
2. The MLFlow server will [proxy access to S3 storage](https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access)

# Acceptance Criteria
Given I visit the URL for the deployed tracking server When I follow the GlobusAuth flow Then I can see the tracking server

Given I visit the URL for the deployed tracking server When I provide invalid Globus credentials Then I am not allowed to see the tracking server

**Comment by WillEngler** [comment]
Implemented here https://github.com/Garden-AI/garden-backend/pull/5
