### ISSUE TITLE
Publish SKLearn Model to Registry

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#38]
_As a Garden User I want to publish my model to the registry so others can use it_

# Description
Users can upload their models to the Garden Model Registry with either the Garden CLI or with Garden SDK library calls. To keep this story simple, we will only work with SKLearn model flavors. Future stories will add additional model flavors.

Model names are namespaces with the user's email address.

Models can be uploaded with _extra pip requirements_ or _conda environments_

The command line version of this would be:
```shell
% garden-ai model register --extra-pip-requirements="pymatgen, matminer" --name matminer --flavor sklearn model.pkl
```

Model can be uploaded from the SDK with 
```python
garden.sklearn.log_model(sk_model, "matminer", 
                                             extra_pip_requirements=["pymatgen", "matminer"])
 ```

# Assumptions:
1. Tracking server URL can be set in the `GardenClient` constructor, but is defaulted to the same URL as the Garden backend
2. Passes the Globus Auth token to the server via the `MLFLOW_TRACKING_TOKEN` environment var
3. Implemented as a wrapper around MLFlow.sklearn.log_model function
4. Returns the version number for the published model

# Acceptance Criteria
Given I have an SKLearn model And I have created a garden client When I call `garden.sklearn.log_model` Then I can see the model listed in the Tracking Server UI

Given I have saved a pickled SKLean model When I issue the `garden-ai model publish` command Then I can see the model listed in the tracking server UI

**Comment by WillEngler** [comment]
I propose to change the acceptance criteria to being able to confirm the model is uploaded via the command line somehow. (Maybe something like `garden-ai model list`.)We don't have our ML Flow instance rigged up to allow access via the UI. (AFAIK even if we set up an alternate auth entryway that wasn't the API Gateway, we'd run into the problem of users being able to delete/modify models that don't belong to them via the UI.)
