### ISSUE TITLE
Garden metadata creation

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#4]
_As a Garden Publisher I want to create garden metadata so consumers can easily find my model_

# Assumptions
1. Metadata will include:
 a. Model title
 b. Model description
 c. DataCite information about the submission
2. Data will be defined using [pydantic](https://pydantic-docs.helpmanual.io)
3. The GardenClient interface will expose a [fluent API](https://en.wikipedia.org/wiki/Fluent_interface) starting with a `create_model` method.
4. This story ends with the library writing a JSON file containing this metadata to the user's current working directory 

#Acceptance Criteria
Given I have instantiated a `GardenClient` when I call the `create_garden` with chained metadata setting methods specifying all of the required fields then I will find a JSON metadata file in my current working directory.

Given I have instantiated a `GardenClient` when I call the `create_garden` with chained metadata setting methods, committing a required field then I will receive an exception.

**Comment by WardLT** [comment]
An example JSON file
```json
{
  "dlhub": {
    "version": "0.9.8",
    "domains": [
      "biology"
    ],
    "visible_to": [
      "public"
    ],
    "name": "iris_svm",
    "files": {
      "model": "model.pkl"
    },
    "dependencies": {
      "python": {
        "scikit-learn": "1.0.2"
      }
    },
    "test": null,
    "type": "servable"
  },
  "datacite": {
    "identifier": {
      "identifier": "10.datacite/placeholder",
      "identifierType": "DOI"
    },
    "creators": [],
    "titles": [
      {
        "title": "Example Scikit-Learn Model",
        "type": null,
        "lang": null
      }
    ],
    "publisher": "DLHub",
    "publicationYear": "",
    "subjects": [],
    "resourceType": {
      "resourceTypeGeneral": "InteractiveResource"
    },
    "contributors": [],
    "descriptions": [],
    "language": null,
    "alternateIdentifiers": [],
    "relatedIdentifiers": [],
    "rightsList": [],
    "fundingReferences": [],
    "version": null
  },
  "servable": {
    "type": "Scikit-learn estimator",
    "shim": "sklearn.ScikitLearnServable",
    "model_type": "SVC",
    "model_summary": "SVC(C=1, kernel='linear', probability=True)",
    "methods": {
      "run": {
        "input": {
          "type": "ndarray",
          "description": "List of records to evaluate with model. Each record is a list of 4 variables.",
          "shape": [
            null,
            4
          ],
          "python_type": null,
          "item_type": {
            "type": "float",
            "description": null,
            "shape": null,
            "python_type": null,
            "item_type": null,
            "element_types": null,
            "properties": null
          },
          "element_types": null,
          "properties": null
        },
        "output": {
          "type": "ndarray",
          "description": "Probabilities for membership in each of 3 classes",
          "shape": [
            null,
            3
          ],
          "python_type": null,
          "item_type": {
            "type": "float",
            "description": null,
            "shape": null,
            "python_type": null,
            "item_type": null,
            "element_types": null,
            "properties": null
          },
          "element_types": null,
          "properties": null
        },
        "parameters": {},
        "method_details": {
          "method_name": "predict_proba"
        }
      }
    },
    "options": {
      "serialization_method": "pickle",
      "classes": [
        "setosa",
        "versicolor",
        "virginica"
      ],
      "is_classifier": true
    }
  }
}
```

**Comment by WardLT** [comment]
I think differently about our initial needs for a manifest:

- Follow an existing schema language for describing input/output data structures (e.g., JSON, MLFlow)
- Be able to support functions with multiple inputs and keyword arguments (i.e., any Python function)
- Be created before publication either "by hand" or via the assistance of a Python SDK
- Passed to a `publish_model` method that submits manifest and any files marked as necessary to web interface
- Support publication-ready metadata (e.g., DataCite) describing the model

A few key differences:
- Open to other standards besides MLFlow (not that I'm opposed to using someone else's work)
- Model description is made before calling publish to lower the complexity of the publish operation

**Comment by WardLT** [comment]
These requirements are ideas we used when creating the DLHub SDK: https://dlhub-sdk.readthedocs.io/en/latest/servable-publication.html

The input descriptions are based off of the JSON schemas (but extensions to include), we use DataCite to describe citation information, and describe the how to build the container with repo2docker. Descriptions of the inputs are built using "helper classes" in an SDK based on pydantic, which facilitates writing them out to disk as JSON

@ascourtas was working on a better version of the documentation

**Comment by blaiszik** [comment]
We should agree on initial schemas for:

1. Model information (evaluate MLFlow, DLHub, HF schemas)
2. General information (e.g. authors, titles, etc. via Datacite)
3. Testing information (e.g., results of reliability testing)
4. Benchmarks

The goal is to create example records so that we can begin work on the front end ASAP

**Comment by ascourtas** [comment]
strawman schema could be good for acceptance criteria for this sprint

**Comment by ascourtas** [comment]
Hm if we want to get this done this sprint, perhaps we should meet to iron out the specifics Ben outlines above? So we can all reach consensus 

@BenGalewsky @blaiszik @WardLT @kjschmidt913

**Comment by ascourtas** [comment]
We decided to split this out into a design issue, to be done in sprint 3, so we can then work on this issue in later sprints
