### ISSUE TITLE
Execute Registered Pipeline

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#40]
_As a Garden User I want to execute a funcx-registered Pipeline so I can execute it remotely, on a known endpoint, and obtain the correct output from local inputs_

# Description
Look up the funcX function ID from the database.json
Endpoint UUID will be defaulted. Baked into the client code.
Calls funcx.run
Block on the task completing

```python
wine_pipeline("All day rose", endpoint="123-45-56")
```

# Assumptions:
1. Container has been built and registered with funcX (#89)
2. Pipeline function has been registered with funcX (#51)
4. `Pipeline.__call__` will have a keyword argument for the endpoint uuid

# Acceptance Criteria
Given I have published a model When I invoke the pipeline (`__call__` magic method) Then a funcX task will be executed on the endpoint that returns my expected results

**Comment by OwenPriceSkelly** [comment]
see: https://github.com/funcx-faas/funcX/pull/1083
