### ISSUE TITLE
First-class support for quality control functions

### ISSUE THREAD

**Issue by WardLT** [Garden-AI/garden#41]
_Machine learning models should not be treated infallible. As everywhere, "garbage in, garbage out." We need to make it easy for contributors to provide a way for specifying uncertainties of model predictions to alert users to potentially-problematic predictions_

# Assumptions:
1. Users can define their methods for assessing prediction uncertainty as a Python function ("quality control" functions)
2. The "quality control" functions takes the same inputs as the machine learning model used to make predictions
3. Both the prediction and quality control values should be passed together back to a user

# Acceptance Criteria
Given I have a model and QC function I want to publish, when I go to publish them then I don't have to write custom code to get both model and QC to run together

**Comment by WillEngler** [comment]
Closing stale tickets today.

I think the publishing system we've arrived at accommodates this, as we've seen with a Wisconsin entrypoint that can pass back error bars along with predictions. We don't have a dedicated way to designate what's quality control and what's a model, but with plain Python this is very doable. 

I won't be surprised if we revisit QC functions soon though.
