### ISSUE TITLE
Garden Create Pipeline

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#47]
_As a model publisher I want to be able to add a pipeline to my ~garden~ life so I can ~thematically organize~ contain(?) my models_

# Description
For this story we will add the `garden-ai create pipeline` command to the CLI. This creates a new pipeline ~in the garden~.

It takes command line arguments to pick up all of the mandatory pipeline properties. If command line args are missing it will prompt for values wizard style.

The command generates a pipeline uuid and adds an entry to the `pipelines` list in `garden.json`

The command creates and populates a templated `{specified_or_current_directory}/{pipeline_name}/pipeline.py`  and empty package dependency files. 

# Assumptions:
1. could use a templating library like [jinja2](https://jinja.palletsprojects.com/en/3.1.x/)
2. `GardenClient.register_metadata` should read/write "local storage" which is a single file like `~/.garden/data/db.json`
    -  could be a good time to implement a little `show_gardens` / `show_pipelines` method for the client 
4. pipelines will need explicit authors rather than inferring them from enclosing garden (relax current default assumption of at least 1 garden per pipeline)
5. firm up CLI command word order (SVO vs SOV; verb-first like `garden create {garden, pipeline}` or object-first like `garden {garden, pipeline} create`? does `garden-ai garden {verb}` look less silly than `garden garden {verb}`?)
    - leaning towards noun-first, which is a slight refactor in the CLI but matches our sdk modules more closely, which seems convenient
7. templated file should contain instructive comments so users aren't surprised by e.g. type-hint annotations being required
8. there should be an entry in the local db (and so a UUID) for the pipeline before the templated file is created 
9. pipelines will need a valid python identifier, the CLI should validate this before creating a pipeline

**Comment by WillEngler** [comment]
Alternate assumptions:
1. The templated file will be called [YourPipelineIdentifier].py
2. Creating a pipeline will not modify garden.json. (You need to explicitly add a pipeline to a garden)

Otherwise, same as Ben G wrote.

**Comment by ascourtas** [comment]
mostly done, still need to finalize Ginja component
