### ISSUE TITLE
Garden pipeline add model

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#48]
_As a model author I want to publish my model so it can be used within a Garden pipeline_

# Description
This can be done with a garden cli command as well as garden SDK calls. This is a wrapper around the various MLFlow `log_model` calls.  

The command will accept a path to a saved model file. The SDK calls can accept a path or a loaded model object of the correct library.

The operation requires a garden.json file it will search in the current working directory first and then travel up to enclosing directories until it is found. The garden.json file is used to find the URL of the model repository server, as well as to lookup pipeline UUIDs from a pipeline name.

The operations require a pipeline name and a model name. When the model is uploaded to the model repository, the name will be prefixed with the pipeline UUID followed by a dot.

This operation will create an MLFlow run since all model uploads have to be in the context of a MLflow run ID.

```
garden pipeline add model --pipeline soup_rating my-model.skl
```

The operations will accept the following optional arguments:
- pip_requirements
- extra_pip_requirements

# Assumptions:
1. Models only exist as part of a pipeline (no garden level models)
2. For this story we will only support the following model flavors:
    1. sklearn
    2. PyTorch
    3. TensorFlow

**Comment by OwenPriceSkelly** [comment]
are we imagining this garden cli command happening before the model is usable by the #50 implementation?

**Comment by WillEngler** [comment]
I think this is superseded by #38
