### ISSUE TITLE
Publish creates a container

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#49]
_Short description_

# Description
Invokes the funcx `build_container` function to support a specific pipeline.

This function accepts a `container_spec` instance:
- Name (the pipeline uuid)
- List of pypi packages or a conda environments
- Needs a publicly readable http endpoint with a zip file (or a GitHub repo)

List of dependencies will be computed as a union from the list of steps.
- model steps will retrieve dependencies from the MLFlow model repository.
- Non-model steps will present the contents of the pipeline's requirements.txt

Zipfile endpoint will be the garden's Git URL

# Assumptions:
1. Validate the requirements for internal consistency if there are multiple models this could be tricky!
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
Stale issue, implemented by various v0 tickets
