### ISSUE TITLE
Step decorator @inference_step

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#50]
_As a pipeline author I want to invoke a published model so I can perform inference in my pipeline_ 

# Description
Decorator for garden pipeline step. Accepts the following arguments:
* model_name - required
* model-version - optional, defaults to `Production`

The model name must be a fully qualified name used in the model register command. The model-version may be a number or a _stage_ identifier from the MLflow model repository.

Wraps the function with code to:
1. Generate the model URI
2. Download the model from from MLFlow repository
3. Invoke the model using the pyfunc flavor.

```
@inference_step(model="mat miner", version="1")
def mat_miner(dataframe):
 pass

```

# Assumptions:
1. Assumes that the decorator expands at garden publish time

# Acceptance Criteria
Given I have a step decorated as `@inference_step` And the model exists in the repository with the indicated version When I call the pipeline Then the model is invoked.

**Comment by OwenPriceSkelly** [comment]
how would we feel about this syntax instead?
```python3 
@step # normal step decorator
def mat_miner(
    model: garden_ai.Model(model_id=..., version=...), # cues us to inject MLflow code 
    dataframe: pd.DataFrame,
) -> MyResultType:
    # do something with `model`, even if previous step only returned a dataframe 
    pass
```
this is inspired by how e.g. pydantic and typer/click use more specialized type hints; pydantic class variables can be annotated `x: pydantic.Field(...)` and typer infers whether something is an arg or an --opt by having args annotated `x: typer.Option(...)` or `a: typer.Argument(...)`

**Comment by BenGalewsky** [comment]
Would this fall foul of the [cute way Python handle default arguments](https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument)? or is this morally equivalent to the decorator?

**Comment by OwenPriceSkelly** [comment]
good point -- I'll think about it a bit more but my impression is that they should be morally equivalent; in either case the code is only evaluated once at definition time

**Comment by OwenPriceSkelly** [comment]
I'm leaning toward the "default value" syntax over the "special decorator" syntax originally proposed for a couple reasons: 
1. it'll be easier to implement. this is less significant for v0, but for contributors outside of our team I think it'll much friendlier to implement `garden_ai.PrettySpecialModel` by subclassing a hypothetical `garden_ai.Model` than to implement a `@pretty_special_step` decorator; unless you have had a good reason to write a decorator at some point before, you probably don't know/care how they de-sugar off the top of your head
2. more pythonic in the sense that several very popular python libraries (pydantic, typer, fastapi, attrs) as well as `dataclasses.field` use this kind of hybrid annotation-with-dynamic-default-value, so I don't think it'd unbearably verbose (though more verbose than the purely-decorator style)

**Comment by OwenPriceSkelly** [comment]
...
3. less magical -- the user would have to type `model.predict(dataframe)` in the body of their function, rather than having us inject that line automatically
