### ISSUE TITLE
Pipeline register creates funcX function

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#51]
_As a pipeline author I want to register my pipeline with funcX so others can call my pipeline_

# Description
Given a specific pipeline name:
1. Compose the function from the pipeline
2. Call funcx.register_function(composed_function, container_id)
3. Save the resulting function uuid to database.json

# Assumptions:
1. We already have the container uuid from a previous step in the publish workflow
4. 

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
I have a WIP PR that seems to work but needs more testing: https://github.com/Garden-AI/garden/pull/90. 

Back-burnering this temporarily to pick up an infra ticket
