### ISSUE TITLE
New User Story

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [Garden-AI/garden#69]
_As a new user who's only ever heard of garden, I will be interested in knowing what Garden is and what it's used for_

# Assumptions:
1. The front page of the docs should have enough information for new users to understand the full purpose of Garden AI
2. The front page of the docs should contain an example of what it's like to use Garden vs what it's like to not use Garden

Something like https://docs.xarray.dev/en/stable/index.html is what I'm envisioning here.

**Comment by WillEngler** [comment]
It's still evolving, but Owen has a first stab at a docs page up now so I'm gonna say we're good to close now. (But please feel free to chime in with suggestions on more things that should be in the docs)

https://garden-ai.readthedocs.io/en/latest/architecture_overview/
