### ISSUE TITLE
Investigate the model publication and usage flow for HuggingFace

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#8]
_As Developers, we want to investigate existing services that are similar (eg HuggingFace) to see where they shine and where they falter_

# Assumptions:
1. The HuggingFace API is accessible via https://huggingface.co/models 
2. I can install the HuggingFace Python SDK locally

# Acceptance Criteria
Given I have presented my findings to the team (either in bullet points or 1-3 slides, whatever I find easiest), we can all list out:
- What HuggingFace does well for model publishing
- What HuggingFace does not do well for model publishing
- What components we could potentially reuse for Garden
- Whether or not we'd want to reuse those components

**Comment by WardLT** [comment]
>  we can all list out:

That's a really good acceptance criteria!

**Comment by ericblau** [comment]
I have a google doc that contains a bullet point summary of my HuggingFace research, followed by some notes.  [Here's the doc](https://docs.google.com/document/d/1TFmBlSEVA2QQnOWFjTG_buXybR3smAHRLMQYkvW5GH0/edit?usp=sharing)

**Comment by Aadit-Ambadkar** [comment]
[My notes](https://docs.google.com/document/d/1irHNGvh64zflHzXqr8-hCvQDj9hS014V8YrW1t7XRuc/edit?usp=sharing). Significantly less thorough than @ericblau's but still hopefully still useful
