### ISSUE TITLE
As a user of Garden-Ai I would like the quickstart.rts to have updated CLI info

### ISSUE THREAD

**Issue by steve-barnard** [Garden-AI/garden#81]
_Short description_

After following the [quickstart docs](https://github.com/Garden-AI/garden/blob/main/docs/quickstart.rst) I was unable to follow them literally. My tired brain struggled for a bit then Will was able to assist me in discovering the necessary prefix of garden-ai prior to the other CLI args/params.

Creating the issue for documentation; this looks like an easy fix, but I was not sure if auto docs (Sphinx) created the quickstart. If not might be a simple update.

# Assumptions:
1. Appears the quickstart should have the preface of ```garden-ai garden create --help``` rather than the bare ```garden create --help```
2. Assumption that the previous docs might have been acting directly on the repo/local use of garden, when installing via pip the prefix of **garden-ai** appears to be required.
3. Can reproduce via following exact lines on the quickstart.

# Acceptance Criteria
Given the [quickstart docs](https://github.com/Garden-AI/garden/blob/main/docs/quickstart.rst), when the user follows them, then they are able to successfully get proper CLI responses.

**Comment by WillEngler** [comment]
Closed by #83
