### ISSUE TITLE
Example Showing Comparison of Pipeline Predictions to Known Values

### ISSUE THREAD

**Issue by blaiszik** [Garden-AI/garden#86]
The example shown in the group meeting on March 17th showed a pipeline run locally containing a step with a model that predicted molecular ionization potential with an input SMILES. The dataset used did not have the output (ionization potential) so metrics could not be calculated to see how the model performed.

**Why is this important?** This story is on the path of first demo of automatically testing a model's performance on a predictive task defined against a dataset - a key function in the Garden proposal.

**Expected effort level:** This should be fairly straightforward if we can get a matched dataset and model from Logan or Ryan Jacobs.

# Assumptions:
1. A dataset (D) is loaded from Foundry
2.A pipeline running locally (or via funcX) contains a model that has an input that is an input in the dataset (D) and an output that is a target in dataset D
3. The pipeline is run with inputs from D and tested against targets from D

# Acceptance Criteria
Demo shown  or notebook/code uploaded with and a metric calculated (e.g., mean absolute error) between the dataset and pipeline in question

**Comment by WillEngler** [comment]
Whoever picks this up, ask @blaiszik for how we should approach

**Comment by ascourtas** [comment]
basically done once Logan gives us the metadata (maybe 30 min work)

**Comment by WillEngler** [comment]
Closing as stale
