### ISSUE TITLE
Invoke pipeline from garden object

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#96]
When a user pulls a Garden down from Globus Search (or instantiates one from local data store), it should have pipelines as child attributes that the user can invoke like so:

```
garden = gc.get_garden_by_doi(ALICE_GARDEN_DOI)
print(garden.CrystalStructurePredictor(df))
```

# Assumptions:
1. If there are multiple pipelines with the same shortname in the garden, the user will have to grab the pipeline with a DOI. `garden.pipelines[doi]`
2. OR: just explode

# Acceptance Criteria
Given a Garden object in the SDK, when I want to execute a pipeline in that garden remotely, there is a convenient way to access a handle to the FuncX wrapper for it on the garden object.

**Comment by ascourtas** [comment]
nearly done
