### ISSUE TITLE
Add model metadata to database and enable linking Foundry data used for training

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#97]
We want to be able to link models to data they were trained on.

# Assumptions:
1. There will be a new top-level `models` object in the local data.json.
2. Each model has an optional linked_dataset field

# Acceptance Criteria
Given I search for a Garden that contains a pipeline that contains a model that was trained on a Foundry dataset, when I query it I see a link to the Foundry metadata in the returned record.

**Comment by OwenPriceSkelly** [comment]
should we fold the `garden-ai model list` cli command into this story, since this is the story for the metadata that would be listed? or should those be different stories

**Comment by WillEngler** [comment]
Probably time to incorporate Ben's connection schema: https://docs.google.com/document/d/1t0EeLSYB-UPaHs7zb8FZGYEqbfhNZXZB2iAewST3GwY/edit

**Comment by WillEngler** [comment]
This ended up being pretty big so I needed to split it up. Phase 1 is up for review: https://github.com/Garden-AI/garden/pull/121

Also sorry I missed your question Owen ...

> should we fold the garden-ai model list cli command into this story, since this is the story for the metadata that would be listed? or should those be different stories

I'm fine either way, but I'd lean to not including it because this task is already pretty big.

**Comment by WillEngler** [comment]
Also now that we have data in the "database" we can do something like `cat ~/.garden/data.json | jq ". | {models}"` as a workable model list command for now 😄
