### ISSUE TITLE
Make good enough documentation for users

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#98]
As v0 completion criteria, there should be easy to understand documentation on how to create, publish, and use gardens.

# Assumptions:
1. 

# Acceptance Criteria
Given I am someone who wants to use Garden, when I go on the internet looking for how to use it, there is a place with thorough information telling me how to use it.

**Comment by WillEngler** [comment]
Potentially covered by #163?

**Comment by OwenPriceSkelly** [comment]
^^I think if this story is "good enough for v0/vlogan users" then #163 covers it, we can open a new v1+ user docs story when we get there
